=head1 NAME

karemote - issue a remote command as root on the deployed nodes.

=head1 SYNOPSIS

B<kaaddkey>  [B<-m|--machine> hostname] [B<-f> nodefile] [B<-c|--command> "remote command"] [B<-v|--verbose>]

=head1 DESCRIPTION

karemote can be seen as a B<frontend to ease the creation of user's scripts> to ease experiments configuration on a set of deployed nodes.

Karemote is used in kaaddkeys.

This command is used to run a remote command as root on a set of deployed nodes.
The target nodes should be deployed on an user's authorized partition to ensure proper execution of the command.

=head1 OPTIONS

=over

=item B<-m|--machine> hostname

Specifies a target host. This option can be used more than once to specify several target hosts.

=item B<-f> nodefile

Specifies a file containing a set of target nodes.

=item B<-c> "remote command"

Specifies a command to run on target nodes as root.


=item B<-v, --verbose>

verbose mode.

=back

=head1 EXAMPLE

Echo coucou as root on all the nodes:

=over

=item karemote -f $OAR_NODEFILE -c "echo coucou"

=back

=head1 SEE ALSO

kaaddkeys(1)

=head1 COPYRIGHTS

This software is licensed under the GNU Library General Public License. There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
