=head1 NAME

karecordenv - registers an environment.

=head1 SYNOPSIS
 
B<karecordenv> [B<-n  | --name> registration_name]
    B<[-v  | --version> version]            # default is 1
    B<[-d  | --description> description]
    B<[-a  | --author> author_email]
    B<[-fb | --filebase> environment_image_path]
    B<[-ft | --filesite> post-installation_file_path]
    B<[-s  |  --size> sizeMo]
    B<[-i  |  --initrdpath> initrdpath]        # default is none
    B<[-k  |  --kernelpath> kernel_path]
    B<[-p  |  --param> kernel_param]
    B<[-fd | --fdisktype> fdisk_type]         # default is 82
    B<[-fs | --filesystem> file_system]        # default is ext2
    B<[-fe | file_environment> file_environment]

Name, kernel_path, environment_image_path and post-installation_file_path must be defined.

=head1 DESCRIPTION

karecordenv registers an environment for the current user in order to be able to use it with the deployment system.

=head1 OPTIONS

=over

=item B<-n|--name> registration_name

the registration name for the environment

=item B<-v|--version> version

the version number of the environment (if needed) ; I<default is 1>

=item B<-d|--description> "description"

a brief description of the environment

=item B<-a|--author> author_email

the author email address

=item B<-fb|--filebase> environment_image_path

the complete path to the environment image

=item B<-ft|--filesite> post-installation_file_path

the complete path to the post-installation file

=item B<-s|--size size> (Mo)

the size of the environment ; in order to perform partition size check before a deployment

=item B<-i|--initrdpath> initrd_path

the complete initrd path in the environment (including intrd name)

=item B<-k|--kernelpath> kernel_path

the complete kernel path in the environment (including kernel name). You have to use "chainload" keyword, when deploying a "dd" image

=item B<-p|--param> kernel_parameters

arguments passed to kernel at boot (I<root> parameter is set automatically), if left empty, default are configured by local administrator

=item B<-fd|--fdisktype> fdisk_type

the fdisk type ; I<default is 82>

=item B<-fs|--filesystem> file_system

the file system type ; I<default is ext2>

=item B<-fe|--file_environment> file_environment

records an environment from file

=back

=head1 EXAMPLE

=over

=item karecordenv -n debian -v 2 -d "debian maison" -a katools@imag.fr -fb file://home/nis/jleduc/ImagesDistrib/image_Debian_current.tgz -ft file://home/nis/jleduc/Boulot/postinstall/traitement.tgz -size 650 -k /boot/vmlinuz -i /initrd -p "console=ttyS0,38400n8 ETH_DRV=tg3" -fd 83 -fs ext2

Registers a debian image whose features are explicitly given in parameter

=back

 $cat > /home/deploy/environments/debianMin/image.dsc << EOF
 name = debianMin
 description = debian minimal environment
 author = Julien Leduc
 filebase = file://home/deploy/environments/debianMin/image.tgz
 filesite = file://home/deploy/environments/debianMin/postinstall.tgz
 size = 400
 initrdpath = /boot/initrd.img-2.6.8-1-686-smp
 kernelpath = /boot/vmlinuz-2.6.8-1-686-smp
 kernelparam =
 EOF	

 $karecordenv -fe /home/deploy/environments/debianMin/image.dsc

Registers a debianMin environment from a file.

=head1 SEE ALSO

L<kaenvironments(1)>

=head1 COPYRIGHTS

This software is licensed under the GNU Library General Public License. There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
