#!/usr/bin/perl

use Getopt::Long;
use Term::ReadKey;
use IPC::Open2;
use IO::Handle;
use libkadeploy2::conflib;
use warnings;
use strict;

sub usage();
sub mygetlogin();
sub mygetpassword();
sub mysqlload($);

my $create;
my $drop;
my $clean;
my $testconf;
my $help;
my $addmysqlrights;
my $delmysqlrights;
my $create_db_deploy;
my $create_table_deploy;
my $drop_db_deploy;
my $clean_db_deploy;
my $patch21;
my $patch211;
my $login;
my $password;
my $ok=0;
my $host=libkadeploy2::conflib::get_conf("deploy_db_host");
my $mysqlschemapath=libkadeploy2::conflib::get_conf("kadeploy2_directory")."/share/mysql/";

my $deploy_db_name=libkadeploy2::conflib::get_conf("deploy_db_name");
my $deploy_db_login=libkadeploy2::conflib::get_conf("deploy_db_login");
my $deploy_db_password=libkadeploy2::conflib::get_conf("deploy_db_psswd");


GetOptions('addmysqlrights'        => \$addmysqlrights,
	   'delmysqlrights'        => \$delmysqlrights,
	   'create_db_deploy'      => \$create_db_deploy,
	   'create_table_deploy'   => \$create_table_deploy,
	   'drop_db_deploy'        => \$drop_db_deploy,
	   'clean_db_deploy'       => \$clean_db_deploy,
	   'patch21'               => \$patch21,
	   'patch211'              => \$patch211,
	   'h!'                    => \$help,
	   'help!'                 => \$help,
	   );


if ($clean_db_deploy)
{
    $login=$deploy_db_login;
    $password=$deploy_db_password;
    mysqlload("clean_db_deploy");
    $ok=1;
}

if ($addmysqlrights        || 
    $delmysqlrights        ||
    $drop_db_deploy        ||
    $create_db_deploy      ||
    $create_table_deploy   ||
    $patch21               ||
    $patch211
    ) 
{
    print "!!! Warning it required Mysql administrator right !!!\n";
    $login    = mygetlogin();
    $password = mygetpassword();
}



if ($delmysqlrights)         { mysqlload("delmysqlrights"); $ok=1; }
if ($addmysqlrights)         { mysqlload("addmysqlrights"); $ok=1; }
if ($drop_db_deploy)         { mysqlload("drop_db_deploy"); $ok=1; }
if ($create_db_deploy)       { mysqlload("create_db_deploy"); $ok=1;}
if ($create_table_deploy)    { mysqlload("create_table_deploy"); $ok=1;}
if ($patch21)                { mysqlload("patch-kadeploy-2.1"); $ok=1;}
if ($patch211)               { mysqlload("patch-kadeploy-2.1.1"); $ok=1;}

if ($ok==0 ||
    $help) 
{ 
    usage(); 
}




#######################################END OF MAIN#########################################

sub usage()
{
    print "$0 
\t-addmysqlrights             # create the \"deploy\" user for the db
\t-delmysqlrights             # delete this user from the db

\t-create_db_deploy           # create database
\t-create_table_deploy        # create table
\t-drop_db_deploy             # drop database
\t-clean_db_deploy            # clean deployed and deployement table

\t-patch21                    # patch db 2.0 -> 2.1
\t-patch211                   # patch db 2.1 -> 2.1.1

\t      
\t-clean     correct error in kadeploy database
\t-h|--help print this message\n\n";
}

sub mygetlogin()
{
    my $login;
    print("login:");
    $login=<STDIN>;
    chomp($login);
    return $login;
}

sub mygetpassword()
{
    my $password;
    print("password:"); 
    ReadMode('noecho');
    $password = ReadLine(0);
    chomp($password);
    ReadMode('normal');
    print "\n";
    return $password;
}

sub mysqlload($)
{
    my $func=shift;
    my $ret;
    $ret=system("cat $mysqlschemapath/$func.sql | sed -e 's/SUBSTmydeploypasswordSUBST/$deploy_db_password/g' -e 's/SUBSTmydeployloginSUBST/$deploy_db_login/g' -e 's/SUBSTmydeploydbSUBST/$deploy_db_name/g' | mysql -u $login --password=$password --host=$host ");
    if ($ret==0)
    {
	print("$func Done !!!\n");
    }
    else
    {
	print("Something Wrong occured...");
    }
    return $ret;
}
