#!/usr/bin/perl

use Getopt::Long;
use libkadeploy2::rights_iolib;
use libkadeploy2::conflib;
 
use libkadeploy2::node_bd;
use libkadeploy2::nodes;
use strict;

if (!@ARGV){
    print "Usage : kadelnode [-l|--login login] [-m|--machine hostname] [-p|--partition partition]\n";
    exit 0;
}

## declares the options
my @user_list = ();
my @host_list = ();
my @part_list = ();

## gets the options
GetOptions('l=s' => \@user_list,
	   'login=s' => \@user_list,
	   'm=s' => \@host_list,
	   'machine=s' => \@host_list,
	   'p=s' => \@part_list,
	   'partition=s' => \@part_list
	   );

## checks if needed options are defined
if (!@user_list){
    print "WARNING : no user specified, rights revoked to all users\n";
    @user_list = ("*");
}
if (!@host_list){
    print "WARNING : no host specified, rights revoked for all nodes\n";
    @host_list = ("*");
}
if (!@part_list){
    print "WARNING : no partition specified, rights revoked for all partitions\n";
    @part_list = ("*");
}

## time to revoke rights
my $base = libkadeploy2::deploy_iolib::connect();

foreach my $user (@user_list){
    foreach my $host (@host_list){
	foreach my $device (@part_list){
	    libkadeploy2::rights_iolib::del_user($base,$user,$host,$device);
	}
    }
}

libkadeploy2::deploy_iolib::disconnect($base);

print "Done.\n";

1;
