#!/usr/bin/perl

use Getopt::Long;

my $usage = "Usage : kaaddkey [-k|--key-file public_keyfile] [-m|--machine hostname] -f nodefile\n";

if (!@ARGV){
    print $usage;
    exit 0;
}

## gets the options
GetOptions('m=s'           => \@host_list,
           'machine=s'     => \@host_list,
           'f=s'           => \$node_file,
           'k=s'           => \$keyfile,
           'key-file=s'    => \$keyfile,
           'verbose'       => \$verbose,
           'v'             => \$verbose
           );


my $test = 0;
my $command = "";

if (! -r $keyfile) {
	print "$keyfile is not readable\n";
	exit(1);
}

if ($node_file eq "") {
	foreach my $i (@host_list) {
 		$test = 1;
		$command .= "-m $i "; 
        }
} else {
		$test = 1;
		$command .= "-f $node_file ";
}

if ($verbose) { $command .= "-v ";}

if ($test == 0 ) {
	print $usage;
	exit 0;
}

return (exec("karemote -c \"echo \$(cat $keyfile) >> /root/.ssh/authorized_keys\" "  . $command)); 
