all: 
clean:
distclean:
distdir:
install:
	@echo "nothing to do"
	@echo "prefix $(PREFIX)"
	@echo "user "
	perl -i -pe "s#^DEPLOYDIR=.*#DEPLOYDIR=$(PREFIX)#;;s#^DEPLOYUSER=.*#DEPLOYUSER=$(DEPLOYUSER)#" $(PREFIX)/bin/kasudowrapper.sh

distdir:
	@echo "distdir"


