#!/bin/bash

PID=0
Exit_handler()
{
    kill -9 $PID
}


if [ -x /etc/kadeploy3/load_kadeploy_env ]
then
    KADEPLOY_CONFIG_DIR=/etc/kadeploy3
    export KADEPLOY_CONFIG_DIR
elif [ ! -x $KADEPLOY_CONFIG_DIR/load_kadeploy_env ]
then
    echo "The Kadeploy environment cannot be loaded, please check your configuration"
    exit 1
fi

unset http_proxy
source $KADEPLOY_CONFIG_DIR/load_kadeploy_env

ruby $KADEPLOY_INSTALL_DIR/src/kadeploy_server.rb "$@" &
PID=$!
trap Exit_handler TERM
trap Exit_handler KILL

wait
