#!/usr/bin/perl

# needs a configuration file that should be found at /etc/kadeploy/deploy_cmd.conf

use Getopt::Long;
use lib::conflib;

use strict;

my @host_list = ();

if (!@ARGV){
    print "Usage : kaconsole -m|--machine hostname\n";
    exit 0;
}

## checks if the command configuration file exist
if(!(conflib::check_cmd_exist() == 1)){
    print "ERROR : command configuration file loading failed\n";
    exit 0;
}

## gets the options
GetOptions('m=s' => \@host_list,
	   'machine=s' => \@host_list,
	   );

## checks if option is defined
if (!@host_list){
    print "Usage : kaconsole -m|--machine hostname\n";
    exit 0;
}

## Available variables are :
## - @host_list - list of hosts to reboot

my %cmd = conflib::check_cmd;

foreach my $host (@host_list){
    
    if(!$cmd{$host}{"console"}){
	print "WARNING : no command found for $host !\n";
    }else{
	# debug print
	# print "to be executed : $host -> $cmd{$host}{\"console\"}\n";
	system("$cmd{$host}{\"console\"}");
    }
}
