#!/bin/ash

# 12/03/2004: rambin is now dynamic tmpfs and DNS is working


# global vars
CMD_PARAM=
DEVICE=eth0

# functions

get_param() {
	CMD_PARAM=$(grep $1 /proc/cmdline | sed s/^.*$1=// | sed s/\ .*//)	
}

boot_failed() {
    reboot -f
}

# mount proc
mount -t proc none /proc
echo "0x100" > /proc/sys/kernel/real-root-dev


# mount a tmpfs ramdisk in /mnt/rambin
get_param RAMBIN_SIZE
RAMBIN_SIZE=$CMD_PARAM
CMD_PARAM=

if [ $RAMBIN_SIZE ]; then
	echo "Using specified size for rambin $RAMBIN_SIZE..."
	mount -t tmpfs -o size=$RAMBIN_SIZE tmpfs /mnt/rambin
else
	echo "Using half the memory size for rambin"
	mount -t tmpfs tmpfs /mnt/ramfs
fi


# in case of many interfaces on the same host
get_param ETH_DRV
ETH_DRV=$CMD_PARAM
CMD_PARAM=

echo "$ETH_DRV"

if [ $ETH_DRV ]; then
    echo "Loading specified ethernet driver $ETH_DRV..."
    modprobe $ETH_DRV
    if [ "$?" != "0" ] ; then
	echo "Failed to load driver... $ETH_DRV"
	boot_failed
    fi
else 
    # should be guessed
    ETH_DRV=$(lspcidrake -f | grep '\[NETWORK_ETHERNET\]' | sed s/\ *\:.*//)
    if [ -z "$ETH_DRV" ]; then
	echo "Fail to detect driver..."
    fi
    echo "Loading guessed ethernet driver: $ETH_DRV"
    modprobe $ETH_DRV
    if [ "$?" != "0" ] ; then
	echo "Fail to load driver... $ETH_DRV"
	boot_failed
    fi
fi


# configure network
if [ $DEVICE ]; then

	DHCP_OK=
	DHCPFILE=/etc/dhcpc/dhcpcd-${DEVICE}.info

	echo -n "Using DHCP for device $DEVICE"
	dhcpcd -n -H ${DEVICE}
	for i in 1 2 3 4 5 6 7 8 9 10 11 12
	do
		echo -n "."
		if [ -r ${DHCPFILE} ]; then
			DHCP_OK=true
			break
		fi
		usleep 2000000
	done
	if [ "$DHCP_OK"=""]; then
		echo "ERROR !"
	else
		echo "OK"
		. ${DHCPFILE}
	fi
fi


#echo "configuring my IP for test"
#ifconfig eth0 192.168.30.2 netmask 255.255.255.0 broadcast 255.255.255.255

#ping 192.168.30.254

echo "nameserver $DNS"
echo "nameserver ${DNS}" > /etc/resolv.conf


inetd -d

#xinetd -filelog /var/log/xinetd.log
