=head1 NAME

clusterpartition.conf - Nodes partition file.

=head1 DESCRIPTION

This  file  describe the nodes partition schema. Actually you can partition only one drive. The syntax is simple, they are only three "class" of line.

=head1 LINE TYPES

The 3 different types of lines possible in this configuration file.

=over

=item B<hda size=80000>

The primary master harddrive named "hda" of the specified "size" (in Mo).

=item B<part=1 size=4000 fdisktype=83 label=empty type=primary>

A first primary partition of 4000 Mo and fdisktype.

=item B<part=5 size=1000 fdisktype=82 label=empty type=logical>

A logical partition included in the extended partition...

=back

B<WARNING>: they are a maximum of 4 primary and 0 extended or 3 primary and 1 extended.

=head1 EXAMPLE

 hda size=8000
 part=1 size=4000  fdisktype=83 label=empty type=primary
 part=2 size=4000  label=empty type=extended

 part=5 size=1000   fdisktype=82 label=empty type=logical
 part=6 size=1000   fdisktype=82 label=empty type=logical

In this schema, you have TWO primary partitions on a 8GB IDE harddrive and Three usable partitions. The two main are 4GB, and the Three real are 4GB, 1GB and 1GB. The extended partition contain logicals partition.


=head1 SEE ALSO

L<kanodes(1)>, L<clusternodes.conf(1)>

=head1 COPYRIGHTS

This software is licensed under the GNU Library General Public License. There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
