#!/usr/bin/perl
use strict;
use warnings;
use libkadeploy2::karights;

my $karights=libkadeploy2::karights::new();
$karights->get_options_cmdline();
exit $karights->run();





################################################################################

