#!/usr/bin/perl

use Getopt::Long;
use libkadeploy2::deploy_iolib;
use libkadeploy2::conflib;
 
use libkadeploy2::node_bd;
use libkadeploy2::nodes;
use strict;

if (!@ARGV){
    print "Usage : kadelnode -m hostname\n";
    exit 0;
}

## declares the options
my @host_list = ();

## gets the options
GetOptions('m=s' => \@host_list,
	   'machine=s' => \@host_list,
	   );

## checks if needed options are defined
if (!@host_list){
    print "ERROR : please enter hostname(s)\n";
    exit 0;
}

my $base = deploy_iolib::connect();

## Available variables are :
## - @host_list

foreach my $host (@host_list){
    deploy_iolib::del_node($base,$host);
}

deploy_iolib::disconnect($base);


1;
