#!/usr/bin/perl

use Getopt::Long;
use Term::ReadKey;
use IPC::Open2;
use IO::Handle;
use libkadeploy2::conflib;
use warnings;
use strict;

sub usage();
sub create();

my $kadeploydir; 
my $tftpdir;
my $pxedir;
my $tftpbootdir;
my $pxelinux;
my $memdisk;
my $deployx86;
my $deployx8664;


my $create;
my $help;

GetOptions('create'                => \$create,
	   'h!'                    => \$help,
	   'help!'                 => \$help,
	   );

$kadeploydir=libkadeploy2::conflib::get_conf("kadeploy2_directory");
$tftpdir=libkadeploy2::conflib::get_conf("tftp_repository");
$pxedir=$tftpdir."/".libkadeploy2::conflib::get_conf("pxe_rep");
$tftpbootdir=$tftpdir."/".libkadeploy2::conflib::get_conf("tftp_relative_path");
$pxelinux="$kadeploydir/lib/pxelinux/pxelinux.0";
$memdisk="$kadeploydir/lib/pxelinux/memdisk";
$deployx86="$kadeploydir/lib/deployment_kernel/x86/";
$deployx8664="$kadeploydir/lib/deployment_kernel/x86_64/";

if ($help)
{
    usage();
    exit(0);
}


if ($create
    )
{
    
}
else
{
    usage();
    exit(0);
}

if ($create) { create(); }


########################################END OF MAIN########################################

sub usage()
{
        print "
$0 
\t-create   Create directory for tftp and pxe

\t-h|--help print this message\n\n";

}

sub create()
{
    system("mkdir -p $tftpdir");
    system("mkdir -p $pxedir");
    system("mkdir -p $tftpbootdir");

    system("cp $pxelinux $tftpdir");
    system("cp $memdisk  $tftpbootdir");
    system("cp $deployx86/*   $tftpbootdir");
    system("cp $deployx8664/* $tftpbootdir");
    print("Done !!!!\n");
}
